### ISSUE TITLE
Tag/release a new version

### ISSUE THREAD

**Issue by kevinburkeshyp** [getsentry/raven-node#113]
There have been lots of changes since 0.7.2

**Comment by gigablah** [comment]
+1. I need parsers to be exported.

**Comment by mattrobenolt** [comment]
0.7.3 published. :) Sorry about that.

**Comment by gigablah** [comment]
:+1:

**Comment by dhritzkiv** [comment]
Is there a new version ready for release? It seems there have been a few changes since `0.7.3`, and the source in my `node_modules` is quite different from the Github repo.

For example, I've noticed that #117 was fixed, the middleware patterns may have changed (resulting in my confusion in #119), and the README was also changed, as a result.
