### ISSUE TITLE
Fingerprint is not used

### ISSUE THREAD

**Issue by 1999** [getsentry/raven-node#147]
https://github.com/getsentry/raven-node/search?utf8=✓&q=fingerprint
https://github.com/getsentry/raven-node/blob/master/lib/parsers.js#L44

Seems like this field is not used at all. As a result I can't set grouped message by myself.
Or am I mistaken and it can be passed another way?

**Comment by mattrobenolt** [comment]
Did you try what the docs say? :) https://docs.getsentry.com/hosted/clients/node/usage/

Code doesn't reference to, but it ends up passing it along untouched if you specify it.

**Comment by 1999** [comment]
Did you mean this?

> fingerprint: The fingerprint for grouping this event.
> {
>     // dont group events from the same NODE_ENV together
>     fingerprint: ['{{ default }}', process.env.NODE_ENV]
> }

Well first: yes I did. Second: if this means grouping then why should I send an array with these values to suppress grouping in one NODE_ENV? How can I pass my own group name?

And why isn't fingerprint used at all in raven-node?
https://github.com/getsentry/raven-node/search?utf8=✓&q=fingerprint

**Comment by mattrobenolt** [comment]
The fingerprint works as a list of components. So in that example, that allows mixing in NODE_ENV for uniqueness and prevent grouping between different environments. That doesn't break grouping entirely, you've just massaged messages into a grouping algorithm so they're not _all_ grouped together.

Alternatively, you could 100% do your own by skipping the '{{default}}' fingerprint too and just send your own string. Fingerprint is an array because it can be comprised of multiple pieces. If you were able to generate your own group name entirely, you could just do: `fingerprint: ['my-unique-group-name']`. If you want to mix it in with the `{{default}}` grouping, you'd do: `fingerprint: ['{{default}}', 'my-unique-group-name']`

And as I mentioned, raven-node doesn't need to reference it since it just gets passed along to the JSON encoded payload sent to Sentry. By you passing it explicitly, will just cause it to tag along with the payload. There's no behavior that raven-node needs to do to support it.

**Comment by 1999** [comment]
Ah, that's the point. I think you should've added this to documentation to clarify fingerprint behaviour.
Still I can't understand this:

> If you want to mix it in with the {{default}} grouping, you'd do: fingerprint: ['{{default}}', 'my-unique-group-name']

What's `{{default}}`? What grouping name will be used if I specify fingerprint: `['{{default}}', 'my-unique-group-name']`?

**Comment by mattrobenolt** [comment]
`{{default}}` is a special token that signals to the server for the default grouping algorithm.

We have a bit more docs on this subject here: https://docs.getsentry.com/hosted/learn/rollups/#customize-grouping-with-fingerprints

**Comment by 1999** [comment]
Now I see. Thank you @mattrobenolt, my bad.

**Comment by 1999** [comment]
Btw, when I use `fingerprint: ['my-unique-group-name']`, it's not used as a group name. Instead standard culprit is used. Sentry version is 7.7.4.

client.process is invoked with args:
```
parsed { extra: 
   { version: '1.2.3',
     description: 'ReferenceError: aa is not defined at http://build/_common.ru.js:52480:25' },
  tags: { type: 'client', url: '/film/251733/' },
  user: undefined,
  level: 'error',
  fingerprint: [ 'my-unique-group-name' ],
  message: 'Error: Uncaught ReferenceError: aa is not defined',
  exception: 
   [ { type: 'Error',
       value: 'Uncaught ReferenceError: aa is not defined',
       stacktrace: [Object] } ],
  culprit: 'lib:sentry at Sentry.captureError' }
```

**Comment by mattrobenolt** [comment]
First of all, the fingerprint doesn't get shown in the UI. It's purely for grouping algorithms. So this should not necessarily be a pretty string, it's typically an md5 hash or something like that.

Lastly, pretty sure Sentry 7.7 didn't support custom fingerprints. I'd have to read through source to verify.
