### ISSUE TITLE
Cleanup error stack

### ISSUE THREAD

**Issue by floriangosse** [getsentry/raven-node#176]
For a cleaner error stack we could use [clean-stack](https://github.com/sindresorhus/clean-stack) which removes the nodejs specific parts in the stack.

**Comment by benvinegar** [comment]
We'd probably keep them but record them as `in_app` `false`.

**Comment by floriangosse** [comment]
This is a nice idea too. :-)

**Comment by benvinegar** [comment]
@LewisJEllis – I don't think we can easily use these libraries, because they wipe the value entirely. We'd like to keep the value, but mark it as being `in_app=false`, so that we can separate application/library frames in the Sentry UI.

So, that probably means borrowing some of these regexes + tests. The stack-utils library probably has [the most readable version](https://github.com/tapjs/stack-utils/blob/master/index.js#L14) of these.

**Comment by LewisJEllis** [comment]
@benvinegar I'm inclined to just depend on stack-utils here; they export that linked `nodeInternals` function, and the rest of the library is small. If node updates and that pile of regex needs to change, we'll only have to worry about updating our dep instead of keeping code in sync. But, I can also see the argument for just plucking that list out and maintaining it ourselves to avoid the dependency; lmk what you think.

**Comment by LewisJEllis** [comment]
@MaxBittker and I investigated this and were unable to make a failing test. `line.isNative()` seems to already return true for node standard library modules. Added passing test case and a couple comments in #271; closing this. Reopen if we find a failing test case or example of a sentry event with node core library frames marked as being in app.

**Comment by MaxBittker** [comment]
@floriangosse do you remember what nodejs frames you saw in the stack?

**Comment by floriangosse** [comment]
No sry, I don't remember.
I think I thought about it more as an enhancement for a cleaner error stack.

**Comment by MaxBittker** [comment]
well, we should be displaying the stack with these frames correctly collapsed in the UI now, so please share if you find anything that looks incorrect 👍
