### ISSUE TITLE
Explore/document source map support for raven-node/Node projects

### ISSUE THREAD

**Issue by benvinegar** [getsentry/raven-node#198]
e.g. for users using TypeScript, CoffeeScript, Babel, etc.

**Comment by benvinegar** [comment]
See also getsentry/sentry/issues/2632

**Comment by benvinegar** [comment]
See also: https://github.com/evanw/node-source-map-support

**Comment by chrisblossom** [comment]
Would love to see this added. I am using Babel with node and this would help tremendously trying to track down node-sentry errors. FYI I currently inline my node sourcemap, but do not have to do that. Not sure if that is helpful information.

**Comment by dpehrson** [comment]
Would like to see this as well. We run an isomorphic react app and because the client is webpacked with file-loader for generating asset hashed filenames, the easiest thing to do is just webpack the server before deployment.

Just verified 2.1.0 fixed the issue so that errors can be reported now, but source map support would make them much more useful.

Really neat service so far.

**Comment by arabold** [comment]
I'm using Webpack with the `devtools: source-map` option and load my source maps using `source-map-support` explicitly, i.e. just like this:
```js
"use strict";
require("source-map-support").install();

// ... regular javascript code ...
```

This does indeed work well. For some reason Raven/Sentry isn't able to show the source code itself, but the file names and line numbers are correct. Not sure why this isn't working but due to this I actually switched to `devtools: nosources-source-map` to save a couple of Kbytes in my upload. But the results are the same. It works fine and gives me accurate call stack information.

**Comment by kamilogorek** [comment]
Aaaaand it's done.
