### ISSUE TITLE
[question] `Error.stackTraceLimit = Infinity` vs. longjohn

### ISSUE THREAD

**Issue by wearhere** [getsentry/raven-node#208]
How does your configuring `Error.stackTraceLimit = Infinity;` [here](https://github.com/getsentry/raven-node/blob/cd3c845644a481368319955a4a1b6158cca1a15b/index.js#L14) compare to the use of the [longjohn](https://github.com/mattinsler/longjohn) library to capture long stack traces, if you know? —What does the longjohn library do that `Error.stackTraceLimit = Infinity` does not?

And is `Error.stackTraceLimit = Infinity` more suitable for [production use](https://github.com/mattinsler/longjohn#production-use)?

Also filed as issue on longjohn [here](https://github.com/mattinsler/longjohn/issues/64).

**Comment by LewisJEllis** [comment]
My basic off-the-top-of-my-head understanding is this:
Any time the current call stack completes, Node goes back to the event loop queue to find the next thing to do and starts a new call stack of sorts to go do that next thing. This is part of run-to-completion semantics.

- By default, Node stack traces are the last up-to-10 frames since the last time Node went back to the event loop queue (i.e. of the current call stack only)
- Setting `Error.stackTraceLimit = Infinity` changes that to "all frames since since Node went back to the event look queue" (the entire current call stack)
- longjohn and similar libraries give you stack traces containing all frames in the call history, not just the call stack since the last visit to the event loop queue (the entire historical call stack, including asynchronous calls, sometimes referred to as an "async stack trace")

Note that just because you pass a function as a callback doesn't mean you're going to cross the event loop boundary and start a new call stack; that callback may be immediately invoked, like by `Array.prototype.map`, by many toolbelt library functions, etc. In general, functions go into the event loop queue precisely when they are passed as a callback to any built-in Node asynchronous API. This means timers, i/o, native event listeners, etc. There may be edge cases to this rule of thumb, and I've never used fibers so I don't know how they fit into that picture.

My understanding is that longjohn and similar libraries are moreso intended for debugging purposes and can have a greater performance impact in production use since you'll *always* be carrying around your *entire* call history. I imagine there are implementation tricks and optimizations such that this has less impact than you might think, but it should still be appreciably more impact than that of `Error.stackTraceLimit = Infinity`. This is why, in `raven-node`, we use `Error.stackTraceLimit = Infinity` but not longjohn.

Contributors to longjohn, Node core, etc probably are more familiar with this stuff than I am, so I welcome corrections to any details I may've gotten wrong above.

**Comment by wearhere** [comment]
Great explanation. Thanks!
