### ISSUE TITLE
It is possible to use raven inside a module?

### ISSUE THREAD

**Issue by felixsanz** [getsentry/raven-node#224]
I have this module:

**error.js**
```javascript
import raven from 'raven'

const sentry = new raven.Client('my dsn')

export default sentry.captureException
```

and then i make use of it by:
```javascript
import reportError from './error.js'

reportError(new Error('foo'))
```

But it doesn't work. I'm getting:

```
/.../node_modules/raven/lib/client.js:165
    var result = self.process(kw);
                     ^

TypeError: Cannot read property 'process' of undefined
    at /.../node_modules/raven/lib/client.js:165:22
    at /.../node_modules/raven/lib/parsers.js:52:5
    at /.../node_modules/raven/lib/utils.js:169:30
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
```

It works fine if i don't setup raven in another file. Why?

Edit: It works if i export `sentry` and then i use `reportError.captureException()`. But why exporting the object works and exporting the method doesn't? Thanks

**Comment by LewisJEllis** [comment]
This is because of how [binding this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind) works and has nothing to do with ES modules.

When you export `sentry.captureException`, that's effectively the same as exporting `raven.Client.prototype.captureException`. It doesn't care or automatically remember that you accessed it via your `sentry` instance.

You could instead do:
```javascript
export default sentry.captureException.bind(sentry)
```
and it should work.

**Comment by felixsanz** [comment]
Oh, `this` again. My bad I should have remembered it. Thanks @LewisJEllis
