### ISSUE TITLE
Sentry error handler should not swallow original error when it itself throws

### ISSUE THREAD

**Issue by jondot** [getsentry/raven-node#253]
Hi,
In cases such as hitting the sentry ratelimit, the error handler will spit out an unexpected error of its own, losing the original error, and bubbling its own rate limit error down the rest of the application handlers.

This middleware should never disrupt the natural error propagation chain when it is in error state, which means, you can consider wrapping these lines:

https://github.com/getsentry/raven-node/blob/master/lib/client.js#L408-L410

with a catch-all try/catch block.

I can submit a PR if you have no objection

**Comment by joaomilho** [comment]
+1

**Comment by LewisJEllis** [comment]
Sorry for the delayed response here - at first glance I thought this was related to the error swallowing issue in #257, and it took me a while to get my thoughts together on that, but now that I revisit I think it's simpler than that.

Wrapping those lines in a try-catch won't solve the problem because `captureException` is asynchronous and the errors that I believe you're referring to are those that might be emitted by the transport later on in the request lifecycle. You can catch them by listening for `error` events from Raven:
```javascript
Raven.on('error', function (err) {
  // there was an error sending a captured exception to sentry
  // handle it however you like, at the very least having this listener here will stop it from blowing up
});
```
I believe this will do what you're looking for, but let me know if you have troubles or your case is different from what I'm imagining. I should document this better, will add to my docs notes.

All-around our handling of rate-limiting is not as nice as it could be; we could have the client automatically slow down, limit request rate, etc. Need to come up with a coherent policy around that.

**Comment by jondot** [comment]
Thanks! From my tests try/catch resolved the issue consistently. But, it might have been a consistent coincidence. I'll check your solution and come back here

**Comment by LewisJEllis** [comment]
In that case, it could well be that you're running into some error other than the ones I'm describing/linked to. I'd be curious to see what `catch (e) { console.error(e.stack) }` spits out with your try/catch wrapper.

**Comment by jondot** [comment]
It was definitely something about rate limit and not being able to deliver the next report. I'm in front of a screen now so I'll reproduce.

**Comment by jondot** [comment]
So, in my attempts to fuzz this, I'm getting a brand new error:

```
$ node --harmony-async-await src/index.js
raven@1.1.1 alert: uncaughtException: bb96b2ec0aad48de8a869dcd9039c309
```
After this the process dies. I've added the error handling bit you've pasted, and still, the process dies. I'm assuming this goes bad on `install()`?

**Comment by LewisJEllis** [comment]
It's hard to say just from that; does that also happen with your try/catch added? Can you boil it down to a simple repro to share so I can play with it? You also might try
```javascript
Raven.on('error', function (err) {
  console.error(err.stack);
});
```
or
```javascript
process.on('uncaughtException', function (err) {
  console.error(err.stack);
});
```
to get the stacktrace.

**Comment by jondot** [comment]
I removed my comment as I didn't want to bother you unless I have a constantly reproducing case :), but you're quick

**Comment by jondot** [comment]
Can't reproduce. I'll classify it as a heisenbug :) I'll close this issue for now but we'll keep close attention to this.
Thanks!

**Comment by LewisJEllis** [comment]
Okay, thanks for letting me know :)
