### ISSUE TITLE
Auto-breadcrumbs break some aws-sdk API calls

### ISSUE THREAD

**Issue by ide** [getsentry/raven-node#273]
When Raven's autoBreadcrumbs option overrides Node's `http` module, it adds behavior that adds a `data` listener to HTTP response streams. This can cause issues because Node's readable streams start out in "paused" mode by default and adding a `data` listener (as well as other conditions described here: https://nodejs.org/api/stream.html#stream_two_modes) put it in "flowing" mode.

The aws-sdk package expects HTTP response streams to be in paused mode. If the stream gets put into flowing mode, aws-sdk doesn't have the right event listener and ignores data from the stream, causing it to get a null response and return an empty object to the user. See https://github.com/aws/aws-sdk-js/issues/1365 for more info.

**Comment by LewisJEllis** [comment]
Hey @ide - thanks for the report. This also came up in #248; I suspected it could be poor interaction with our `data` listener [here](https://github.com/getsentry/raven-node/blob/master/lib/breadcrumbs.js#L103), but hadn't dug into it yet. 

The spot in the AWS SDK that you linked makes it seem pretty clear that that's what's going on. I should be able to change the http instrumentation to grab response details via overriding `ClientRequest.emit` instead of actually attaching a `response` event listener. The change is pretty straightforward, I just need to figure out a good way to test it.

**Comment by LewisJEllis** [comment]
This was closed back in #276 and has been publishes to npm.
