### ISSUE TITLE
Allow to use public API key with `raven-node`

### ISSUE THREAD

**Issue by tchak** [getsentry/raven-node#303]
This is a follow up on discussion we had with @LewisJEllis at Ember Conf. I am currently working on adding support for `Fastboot` (SSR) to `ember-cli-sentry` (https://github.com/damiencaselli/ember-cli-sentry/pull/66) and it would be much simpler if I could use the public API key in both `raven-js` and `raven-node`.

**Comment by mirague** [comment]
Is this a blocker for damiencaselli/ember-cli-sentry#66?

**Comment by tchak** [comment]
@LewisJEllis @getsentry friendly reminder :) Any news on this?

**Comment by mattrobenolt** [comment]
I really don't see us doing this, and it doesn't make sense for us to. Public key authentication here relies on CORS for authentication. It was literally designed for browser based XHR requests, whereas the private key was meant for servers.

**Comment by tchak** [comment]
@mattrobenolt hmm, ok. Thank you for the quick answer. I had a bit more nuanced discussion with @LewisJEllis. The context is usage of sentry in SSR applications. SSR app should have the same requirements in the browser and on the server, and allow for usage of public key in node implementation makes things easier. To go further, I would also suggest to unify the client api in node and browser, or at least provide browser api in node. It will make SSR usage much simpler. But this a different topic.

**Comment by mattrobenolt** [comment]
Here's why this is bad:

Browser security relies on CORS as a method of authentication. On the server, you configure a set of "allowed domains" which controls this.

DSNs with secret keys skip this validation and require you to keep things secret.

If we were to allow raven-node to use public key, that means anyone who gets the public key, can just blast away events without any authentication from any server they want. We've 100% bypassed our attempts at security. 

With that said, raven-js does allow using a private key if you explicitly opt in to allowing it. There are many reasons where you need this, but normal browser scenarios, we would not encourage. 

So fundamentally, browsers and servers are very different and have different security models as well as different runtimes. I'm not sure how to solve the problem here, but we can't allow the server agents to use the public key. You'd have to fake CORS by supplying a fake Origin header just like a browser would do.

**Comment by tchak** [comment]
Again, thanks for detailed and quick answer Matt.
> If we were to allow raven-node to use public key, that means anyone who gets the public key, can just blast away events without any authentication from any server they want. We've 100% bypassed our attempts at security.

I am not so much convinced by this argument, because if you concerned that someone will "blast away events", well someone can already do it by using curl with Origin header... But hey, if this is your last call, I will just have to require both keys (public and private) in the ember addon config.

**Comment by LewisJEllis** [comment]
The answer you might be looking for @tchak is that it's not as bad to expose a secret key as you might think - "secret" might not be the best name for it. Details of CORS and what exactly our event ingestion checks for aside, exposing a public key allows an adversary to theoretically send events to your project as they please as long as they properly spoof some headers (not hard). All that the secret part of the key does is make them not have to spoof headers; it doesn't enable any additional privileges. We have users who are shipping secret keys to users in electron and mobile applications and it's not a problem.

It *is* kind of unfortunate in your particular use case, though, where you want to use the same key for both server and browser side, and you'd rather not ship a "secret" key on the browser side, but I really don't think it's that big of a deal to do so. I don't think we can allow the public key to be used from the server for the reasons Matt details, but I wonder if there's not still something we could do that makes this a little nicer. Will give it some thought.

**Comment by tchak** [comment]
Thank you both for the input!

**Comment by mattrobenolt** [comment]
Yeah, I'd just say if this is absolutely necessary, the better answer it to just use the private key in the browser which would bring us back to the same security concern, rather than allowing the server to use public key. 

Sorry, I'm not trying to be unconstructive here, just leaving information so decisions can be made the best possible.

**Comment by arschmitz** [comment]
This whole discussion and he idea that it's about security is pretty silly. @mattrobenolt do you really think there is a single person that would have the knowledge and desire to spoof logs to sentry does not also have the knowledge to change an origin header? I mean it's a single extra line in almost any server language to add a header. The public key is always going to be exposed and so this attack vector will always be open. By having the public and private key all your doing is giving a very false sense of security to sentry users as you provide no extra real security either way. To go a step further any chance that someone might not realize its a cors issue has been destroyed by you documenting the requirements to fake the request here in this issue. 

To be honest i think the outcome of this issue makes little difference since there is in the end very little difference between the public and private keys. The whole thing is really just an annoyance to developers in the name of supporting fake attempts at security. To me your explanation of "security" and the reason for having the public and private keys only leads to one conclusion which is that having or using 2 keys is pointless and that really in the end even having the public key is pointless. This is at best the smallest of misdirections not security.

**Comment by tchak** [comment]
@arschmitz I am not sure about the difference in public/private keys for sentry, but in most cases there should be a difference. Private key should be the only one allowing for destructive operations. And I agree with you, advocating for it use in mobile or electron apps is not something I would do... What I was hoping for is that `raven-node` with public key would have a restricted access to functionalities, just like browser `raven-js` dose I guess.

**Comment by tchak** [comment]
Regarding the initial issue with `ember-fastboot` support, I will implement two configuration fields, with only public one exposed to the browser.

**Comment by arschmitz** [comment]
@tchak yes in general that is the case but it was indicated above the only difference is the cors validation and that it's safe to use it in the browser. 

> All that the secret part of the key does is make them not have to spoof headers; it doesn't enable any additional privileges.

**Comment by LewisJEllis** [comment]
We're not under any sort of illusion about the fact that a motivated individual can easily send events to a Sentry project that isn't theirs, as is inherent to any frontend-report-to-server situation, and we certainly aren't giving any users any impression of security that isn't there. Maybe the term "secret key" is misleading here (I certainly think so) and maybe readers make assumptions that we do not state, but we certainly do not make any false promises of security. I've worked against malicious automation at a security company in the past, so I know what it means to say something is secure/hard vs saying something is slightly more work but still easy (which is the case here). Just because I discuss what an adversary needs to do to send an event doesn't mean I claim any form of security against them doing so.

What this model *does* tangibly protect against, though, is if someone (intentionally or accidentally) puts your public DSN on their raven-js install (on their high-traffic site) and starts having their visitors and their otherwise-benevolent browsers send events to your project. That's not a security solution in the strictest sense, but it solves a real problem.

I've brought up the "why can't we just get rid of the 'secret key' component and simplify this in our DSNs" question internally; the difficulty is that we need to keep this CORS check in place for the above scenario, and some projects receive events from both raven-js and a server SDK (our Django integration does this automatically), so we can't just say "this project accepts events only from following URLs" or "this project accepts any events without origin/CORS check"; we either lose functionality or we lose the above mitigation.

I think the appropriate resolution to this is just to improve the documentation of DSNs to 
1) better explain the difference/appropriate use of each type (right now there's basically no explanation)
2) avoid the term "secret key" if possible; we could differentiate, for example, by calling the public-key-only DSN a "browser DSN" and the public-and-secret-key DSN a "non-browser DSN"

**Comment by scosman** [comment]
One additional use case: some apps ship node on the client (Electron most notably). It would be nice to not have to expose the secret. After reading this thread it sounds like the "secret" isn't secret at all, so we can ship that. However, the terminology brought me here so it would be worth updating.

**Comment by mazondo** [comment]
Been hitting my head against this for a while, the only answer here that makes much sense is the one from @LewisJEllis .  The fact is that if these things really do expose the same functionality, then it's an annoying distinction but I can live with it.

Unfortunately, until your official documentation SAYS that, I don't trust exposing our secret keys in the browser.  It's got the word secret right on the tin.

If we can get official clarification on the secret key still being restricted to event writing only, then I think it would clear up a lot of this.

**Comment by kamilogorek** [comment]
The client supports this feature now, but the server will reject it for some time until we add support.
