### ISSUE TITLE
only show "no DSN provided, error reporting disabled" in production mode?

### ISSUE THREAD

**Issue by francisdb** [getsentry/raven-node#323]
Our test output is full of `no DSN provided, error reporting disabled` console log messages. (we use the express integration)
Could this maybe disabled in some way?

**Comment by LewisJEllis** [comment]
Yes, all Raven alerts can be disabled with:
```javascript
Raven.disableConsoleAlerts();
```
From [docs on "Disable Console Alerts"](https://docs.sentry.io/clients/node/usage/#disable-console-alerts):
> once you have everything set up and going, we recommend disabling them

Closing for now since I think this solves the problem at hand, but I can reopen if we want to discuss the question of "should we behave differently depending on `process.env`" or "should console alerts be off-by-default".

**Comment by francisdb** [comment]
Aha, missed that, was looking in the configuration section and did not see a flag...
