### ISSUE TITLE
Provide a way to figure out if Raven has been installed. 

### ISSUE THREAD

**Issue by turpault-autodesk** [getsentry/raven-node#325]
The Raven browser lib has a member Raven.isSetup() which is useful to figure out if Raven was installed or not. Having a similar feature in raven-node would be interesting.

Right now, when one of the APIs is used without first configuring Raven, the following exception is thrown (from REPL)

```
> var Raven=require('raven');
undefined
> Raven.captureMessage('test')
TypeError: Cannot read property 'user' of undefined
```

**Comment by LewisJEllis** [comment]
Yea, that error has actually come up in issues/support tickets more than once - people running into that error and not realizing that it's just because they never did `Raven.install()`.

If you need a workaround for now, `Raven.installed` is a(n undocumented) boolean property that will tell you if you've done `Raven.install()` (and it also flips back to false if you `Raven.uninstall()` but that's mostly for our testing).

This is definitely something I want to improve, though; Raven-js mostly does it how we want to: if you try to send an event before installing, it refuses and warns you. We could do that (or maybe be even more strict) and provide an `isSetup()` or `isInstalled()` method.

I'll address this in v2.1.0 which should go out sometime next week.

**Comment by shinzui** [comment]
@LewisJEllis  `Raven.installed` is always returning `undefined` for me.

**Comment by LewisJEllis** [comment]
I misspoke in my earlier comment, `Raven.installed` is `undefined` until you do `Raven.install()` and then it should be `true`. Either way you should be able to do `if (Raven.installed) {`.

**Comment by turpault-autodesk** [comment]
Is the Raven.installed something that could be promoted as 'official', i.e. that would still be available in future versions (at least until a major version update) ?

**Comment by LewisJEllis** [comment]
Sure, it's safe to say `.installed` won't go away on 2.x, but I won't add anything to the docs (outside of these comments) until we have an `isSetup()` or `isInstalled()` method.

**Comment by kamilogorek** [comment]
`Raven.installed` should be sufficient for use-cases like this. Please feel free to reopen an issue if you think this should be improved.

**Comment by mirague** [comment]
This seems to be `Raven._isRavenInstalled` for us.
