### ISSUE TITLE
Traceback error using CoffeeScript > 1.6.1

### ISSUE THREAD

**Issue by jeromegn** [getsentry/raven-node#47]
CoffeeScript now modifies `Error.prepareStackTrace` and the Traceback module doesn't like that.

That's too bad since the new stack traces show the line numbers for both CS and JS. For now, I've reverted back to 1.6.1, but I intend on coming back to fix this.

**Comment by JoeZ99** [comment]
when I try to do

```coffee
client = new raven.Client( settings.raven_url, {
  stackFunction: Error.prepareStackTrace
});
```

I get in sentry the wrong line number in the stacktrace that is recorded in sentry Ithe line numbers of the stack trace correspond to the -would be- compiled javascript files, but the references in starcktrace point to the .coffee files.

Is there any way of getting node to send the right line numbers (i.e. the lines in the .coffee files)?? no attitude here, just to know if I'm missing something.

**Comment by matthewwithanm** [comment]
@JoeZ99 Have you tried [this](https://github.com/evanw/node-source-map-support)?

**Comment by JoeZ99** [comment]
@chakrit , looks like this fix only stops raven from complaining, but the "stacktrace recorded on Sentry is the JS on instead of COFFEE", It's happening to me , too. Just wanted to check with you that It's not that I'm implementing it poorly, it's just that it can't be done. Have you found any workaround to this?
It would be great that we had proper stacktraces

@matthewwithanm , haven't tested what you said, this whole concept of "source maps" is kinda new to me and I don want to get too caught. can you perhaps point me to a good source of documentation on the topic??

txs!!!!

**Comment by mattrobenolt** [comment]
I barely don't know anything about coffeescript, but I thought coffeescript overwrote the `Error.prepareStackTrace` to provide their own, and I thought we parsed that just fine?

I have honestly no idea.

I'm happy to implement anything if someone can submit a pull request or some more details.

**Comment by matthewwithanm** [comment]
@JoeZ99 Source maps are just a formalized way of mapping positions in a compiled language's output (for example, the JS that CoffeeScript creates) back to the original (CoffeeScript). So instead of getting errors with JS and JS line numbers, you'll get errors with CS and CS line numbers. I don't have any specific resource but Googling "source maps" comes up with a few introductions that seem good. I'm not sure if source maps fix the particular issue you're having though.

**Comment by mattrobenolt** [comment]
I don't think you should need source maps for server side CoffeeScript since iirc they hijack `Error.prepareStackTrace` to yield a proper stack trace in the .coffee source. (I've fixed bugs around CoffeeScript hijacking this and breaking).

And if we can parse the stack trace that they give, there shouldn't be any issues.

**Comment by mattrobenolt** [comment]
To clarify, you'd need a source map if you compiled to JavaScript, then ran the compiled JavaScript, but if you're just running the actual .coffee files, things _should_ work.

**Comment by JoeZ99** [comment]
@mattrobenolt , that's what I thought. I'm running
`coffee node/index.coffee`
and passed the stackFunction argument as described before, I hoped for a real stacktrace to show at sentry, but it didn't! I got the line numbers of the compiled JS files but the references in the stacktrace are from COFFEE and, of course they don't make any sense.

The funny thing is that the stacktrace looks perfectly fine in my node console, properly mapped and everything.

in my console:
```stacktrace
 dbgindex Error: love me or leave me

  at /files/xxxx..coffee:116:15
  at has_access (/files/xxx.coffee:286:10)
  at search (/files/xxx.coffee:58:3)
  at Object.route (/files/router.coffee:16:20)
  at /xxx/index.coffee:75:26
  at b (domain.js:183:18)
  at Domain.run (domain.js:123:23)
  ....
  
```

but in sentry:
```stacktrace
/files/index.coffee ? in Server.<anonymous> at line 80 (application)
/files/index.coffee ? in Object.<anonymous> at line 81 (application)
/files/router.coffee ? in route (application)

/files/xxx.coffee ? in search at line 61 (application)
/files/xxx.coffee ? in has_access (application)
/files/xxx.coffee ? in Object.<anonymous> (application)
```

(well one is revese of the other) but you can see how the sentry's stacktrace is full of quesion marks, because those line numbers correspond to the -would be- compiled JS files, and they point to nothing or wrong places in the COFFEE files.


I kinda of work "half way" :-)

**Comment by JoeZ99** [comment]
also, I thought this (wrong line numbers) was the reason this issue is still open...

**Comment by kamilogorek** [comment]
This issue has been closed due to over a year of inactivity. If anyone feels that it should be reopened, please feel free to reopen it and letting me know. Thanks.
